export const PALETTES = {
  forge: {
    name: "Forge",
    primary: "#6D5EF6",
    secondary: "#111118",
    accent: "#C8F542",
    positive: "#22C55E",
    negative: "#F43F5E",
    neutral: "#94A3B8",
    ink: "#111118",
    muted: "#64748B",
    grid: "#EEF1F6",
    slide: "#FFFFFF",
    series: ["#6D5EF6", "#C8F542", "#22C55E", "#0EA5E9", "#F59E0B", "#F43F5E", "#111118", "#A78BFA", "#14B8A6", "#FB7185"],
  },
  mckinsey: {
    name: "McKinsey",
    primary: "#051C2C",
    secondary: "#2251FF",
    accent: "#00A9CE",
    positive: "#00A9A5",
    negative: "#D0422C",
    neutral: "#8C8C8C",
    ink: "#051C2C",
    muted: "#5C6B73",
    grid: "#E6E9EC",
    slide: "#FFFFFF",
    series: ["#051C2C", "#2251FF", "#00A9CE", "#00A9A5", "#6B7C93", "#D0422C", "#F0B323", "#7A3E9D", "#8C8C8C", "#C5CDD3"],
  },
  bcg: {
    name: "BCG",
    primary: "#00965E",
    secondary: "#0D1C2E",
    accent: "#2BB673",
    positive: "#00965E",
    negative: "#E35205",
    neutral: "#6E7B85",
    ink: "#0D1C2E",
    muted: "#5A6770",
    grid: "#E7ECE9",
    slide: "#FFFFFF",
    series: ["#00965E", "#0D1C2E", "#2BB673", "#147A55", "#6E7B85", "#E35205", "#F4B942", "#3D5A80", "#A8D5BA", "#C9D1D4"],
  },
  bain: {
    name: "Bain",
    primary: "#CC0000",
    secondary: "#1B365D",
    accent: "#E31937",
    positive: "#1B365D",
    negative: "#CC0000",
    neutral: "#97999B",
    ink: "#1B1B1B",
    muted: "#5A5A5A",
    grid: "#ECECEC",
    slide: "#FFFFFF",
    series: ["#CC0000", "#1B365D", "#E31937", "#00629B", "#71C5E8", "#4A4F55", "#B7312C", "#97999B", "#FF6B35", "#D5D6D2"],
  },
  thinkcell: {
    name: "Think-Cell",
    primary: "#1F4E79",
    secondary: "#5B9BD5",
    accent: "#9DC3E6",
    positive: "#548235",
    negative: "#C00000",
    neutral: "#7F7F7F",
    ink: "#1F4E79",
    muted: "#595959",
    grid: "#EDEDED",
    slide: "#FFFFFF",
    series: ["#1F4E79", "#5B9BD5", "#9DC3E6", "#548235", "#70AD47", "#C00000", "#ED7D31", "#FFC000", "#7F7F7F", "#A9D08E"],
  },
  flourish: {
    name: "Studio",
    primary: "#FF5A36",
    secondary: "#1A1A2E",
    accent: "#3DDC97",
    positive: "#3DDC97",
    negative: "#FF5A36",
    neutral: "#8B8BA3",
    ink: "#1A1A2E",
    muted: "#5C5C72",
    grid: "#F1F0F5",
    slide: "#FFFFFF",
    series: ["#FF5A36", "#3DDC97", "#4C6EF5", "#FCC419", "#CC5DE8", "#15AABF", "#1A1A2E", "#FA5252", "#82C91E", "#845EF7"],
  },
  monochrome: {
    name: "Mono",
    primary: "#1A1A1A",
    secondary: "#4A4A4A",
    accent: "#737373",
    positive: "#2F2F2F",
    negative: "#000000",
    neutral: "#8A8A8A",
    ink: "#111111",
    muted: "#555555",
    grid: "#EAEAEA",
    slide: "#FFFFFF",
    series: ["#111111", "#2F2F2F", "#4A4A4A", "#666666", "#808080", "#999999", "#B3B3B3", "#CCCCCC", "#1A1A1A", "#E0E0E0"],
  },
};

export const CHART_TYPES = [
  { id: "fan_chart", name: "Fan / P10–P90", cat: "Markets", shape: "fan", desc: "Forecast bands vs realized" },
  { id: "var_fan", name: "VaR fan", cat: "Risk", shape: "fan", desc: "Loss distribution through time" },
  { id: "underwater", name: "Underwater drawdown", cat: "Risk", shape: "underwater", desc: "Peak-to-trough NAV" },
  { id: "cum_bench", name: "Fund vs benchmark", cat: "Markets", shape: "cum_bench", desc: "Cumulative excess return" },
  { id: "rolling_metric", name: "Rolling Sharpe / vol", cat: "Risk", shape: "cum_bench", desc: "Windowed risk metric" },
  { id: "yield_curve", name: "Yield curve", cat: "Markets", shape: "yield", desc: "Tenor vs yield, multi-date" },
  { id: "ohlc", name: "OHLC / candles", cat: "Markets", shape: "ohlc", desc: "Open-high-low-close bars" },
  { id: "brinson", name: "Brinson attribution", cat: "Attribution", shape: "brinson", desc: "Alloc / select / interact" },
  { id: "long_short", name: "Long / short book", cat: "Attribution", shape: "long_short", desc: "Contribution by sleeve" },
  { id: "exposure_stack", name: "Gross / net exposure", cat: "Risk", shape: "line", desc: "Long, short, net over time" },
  { id: "corr_matrix", name: "Correlation matrix", cat: "Quant", shape: "corr", desc: "Pairwise ρ, labeled" },
  { id: "factor_heatmap", name: "Factor heatmap", cat: "Quant", shape: "corr", desc: "Loadings across books" },
  { id: "ridgeline", name: "Ridgeline returns", cat: "Quant", shape: "ridgeline", desc: "Density by sleeve / year" },
  { id: "violin_returns", name: "Return violins", cat: "Quant", shape: "ridgeline", desc: "Distribution comparison" },
  { id: "forest", name: "Forest / factor CI", cat: "Quant", shape: "forest", desc: "Estimate with confidence bars" },
  { id: "qq_plot", name: "QQ plot", cat: "Quant", shape: "qq", desc: "Sample vs normal quantiles" },
  { id: "horizon", name: "Horizon", cat: "Quant", shape: "horizon", desc: "Banded dense time series" },
  { id: "vol_surface", name: "Vol surface", cat: "Markets", shape: "heatmap", desc: "Strike × tenor implied vol" },
  { id: "order_book", name: "Order book depth", cat: "Markets", shape: "order_book", desc: "Bid / ask size ladder" },
  { id: "parallel_coords", name: "Parallel coordinates", cat: "Quant", shape: "parallel", desc: "Multi-factor profiles" },
  { id: "alpha_beta", name: "Alpha–beta", cat: "Attribution", shape: "scatter", desc: "Regression vs benchmark" },
  { id: "style_box", name: "Style box", cat: "Attribution", shape: "style_box", desc: "Size × value/growth" },
  { id: "icicle", name: "Icicle", cat: "Part-to-whole", shape: "hierarchy", desc: "Hierarchical partition" },
  { id: "lorenz", name: "Lorenz / Gini", cat: "Quant", shape: "items", desc: "Concentration curve" },
  { id: "candles_volume", name: "Candles + volume", cat: "Markets", shape: "ohlc", desc: "OHLC with volume pane" },
  { id: "pnl_calendar", name: "P&L calendar", cat: "Risk", shape: "calendar_days", desc: "Daily P&L heat grid" },
  { id: "liquidity_ladder", name: "Liquidity ladder", cat: "Risk", shape: "items", desc: "Tenor cash / gap" },
  { id: "mosaic", name: "Mosaic", cat: "Part-to-whole", shape: "mekko", desc: "Conditional share tiles" },
  { id: "grouped_bar", name: "Clustered columns", cat: "Bars", shape: "series", desc: "Side-by-side series" },
  { id: "stacked_bar", name: "Stacked columns", cat: "Bars", shape: "series", desc: "Mix across categories" },
  { id: "100_stacked", name: "100% stacked columns", cat: "Bars", shape: "series", desc: "Share that sums to 100%" },
  { id: "horizontal_bar", name: "Ranked bars", cat: "Bars", shape: "items", desc: "Sorted comparison" },
  { id: "grouped_horizontal", name: "Clustered bars", cat: "Bars", shape: "series", desc: "Horizontal clusters" },
  { id: "stacked_horizontal", name: "Stacked bars", cat: "Bars", shape: "series", desc: "Horizontal mix" },
  { id: "100_stacked_horizontal", name: "100% stacked bars", cat: "Bars", shape: "series", desc: "Horizontal share" },
  { id: "lollipop", name: "Lollipop", cat: "Bars", shape: "items", desc: "Dot + stem ranking" },
  { id: "dumbbell", name: "Dumbbell", cat: "Bars", shape: "dumbbell", desc: "Before vs after" },
  { id: "bullet", name: "Bullet", cat: "Bars", shape: "bullet", desc: "Actual vs target" },
  { id: "range_bar", name: "Range bars", cat: "Bars", shape: "dumbbell", desc: "Low–high spans" },
  { id: "waterfall", name: "Waterfall", cat: "Bars", shape: "waterfall", desc: "EBIT bridge with connectors & hatch" },
  { id: "stacked_waterfall", name: "Stacked waterfall", cat: "Bars", shape: "stacked_waterfall", desc: "Bridge with mix" },
  { id: "waterfall_horizontal", name: "Horizontal waterfall", cat: "Bars", shape: "waterfall", desc: "Bridge, sideways" },
  { id: "pareto", name: "Pareto", cat: "Bars", shape: "items", desc: "Bars + cumulative %" },
  { id: "win_loss", name: "Win / loss", cat: "Bars", shape: "items", desc: "Up vs down periods" },
  { id: "line_trend", name: "Line + CAGR", cat: "Lines", shape: "line", desc: "Trend with growth" },
  { id: "step_line", name: "Step line", cat: "Lines", shape: "line", desc: "Discrete steps" },
  { id: "area_stacked", name: "Stacked area", cat: "Lines", shape: "line", desc: "Mix over time" },
  { id: "area_100", name: "100% area", cat: "Lines", shape: "line", desc: "Share over time" },
  { id: "streamgraph", name: "Streamgraph", cat: "Lines", shape: "line", desc: "Organic mix" },
  { id: "combo", name: "Combo", cat: "Lines", shape: "combo", desc: "Columns + line" },
  { id: "slope", name: "Slope", cat: "Lines", shape: "slope", desc: "Two-period change" },
  { id: "bump", name: "Bump / ranking", cat: "Lines", shape: "line", desc: "Rank over time" },
  { id: "connected_scatter", name: "Connected scatter", cat: "Lines", shape: "scatter", desc: "Path through XY" },
  { id: "pie_donut", name: "Pie / donut", cat: "Part-to-whole", shape: "items", desc: "Share of total" },
  { id: "nested_donut", name: "Nested donut", cat: "Part-to-whole", shape: "series", desc: "Two-ring mix" },
  { id: "treemap", name: "Treemap", cat: "Part-to-whole", shape: "items", desc: "Nested rectangles" },
  { id: "sunburst", name: "Sunburst", cat: "Part-to-whole", shape: "hierarchy", desc: "Radial hierarchy" },
  { id: "waffle", name: "Waffle", cat: "Part-to-whole", shape: "items", desc: "10×10 share" },
  { id: "packed_circles", name: "Packed circles", cat: "Part-to-whole", shape: "items", desc: "Bubble pack" },
  { id: "nightingale", name: "Nightingale", cat: "Part-to-whole", shape: "items", desc: "Rose chart" },
  { id: "polar_area", name: "Polar area", cat: "Part-to-whole", shape: "items", desc: "Equal-angle roses" },
  { id: "marimekko", name: "Marimekko", cat: "Part-to-whole", shape: "mekko", desc: "Width × mix" },
  { id: "scatter_bubble", name: "Scatter / bubble", cat: "Scatter", shape: "scatter", desc: "XY + size, regression, averages" },
  { id: "bubble_matrix", name: "Bubble matrix", cat: "Matrix", shape: "bubble_matrix", desc: "Grid: size × color × label" },
  { id: "quadrant", name: "Quadrant map", cat: "Scatter", shape: "scatter", desc: "2×2 positioning" },
  { id: "beeswarm", name: "Beeswarm", cat: "Scatter", shape: "items", desc: "Distribution dots" },
  { id: "hexbin", name: "Hexbin", cat: "Scatter", shape: "scatter", desc: "Density bins" },
  { id: "boxplot", name: "Box plot", cat: "Scatter", shape: "box", desc: "Quartiles" },
  { id: "histogram", name: "Histogram", cat: "Scatter", shape: "items", desc: "Frequency bins" },
  { id: "heatmap", name: "Heatmap", cat: "Matrix", shape: "heatmap", desc: "Grid intensity" },
  { id: "cohort", name: "Cohort", cat: "Matrix", shape: "heatmap", desc: "Retention grid" },
  { id: "calendar_heatmap", name: "Calendar", cat: "Matrix", shape: "heatmap", desc: "Day intensity" },
  { id: "radar", name: "Radar", cat: "Matrix", shape: "series", desc: "Multi-axis profile" },
  { id: "sankey", name: "Sankey", cat: "Flow", shape: "sankey", desc: "Weighted flows with gradients" },
  { id: "funnel", name: "Funnel", cat: "Flow", shape: "funnel", desc: "Conversion drop-off" },
  { id: "chord", name: "Chord", cat: "Flow", shape: "sankey", desc: "Pairwise flows" },
  { id: "alluvial", name: "Alluvial", cat: "Flow", shape: "sankey", desc: "Category flow" },
  { id: "tornado", name: "Tornado", cat: "Compare", shape: "tornado", desc: "Two-sided sensitivity" },
  { id: "diverging_bar", name: "Diverging bars", cat: "Compare", shape: "tornado", desc: "Likert / NPS" },
  { id: "population_pyramid", name: "Pyramid", cat: "Compare", shape: "tornado", desc: "Split population" },
  { id: "gauge", name: "Gauge", cat: "KPI", shape: "gauge", desc: "Progress to target" },
  { id: "kpi_cards", name: "KPI cards", cat: "KPI", shape: "kpis", desc: "Big numbers" },
  { id: "progress_ring", name: "Progress rings", cat: "KPI", shape: "items", desc: "Circular completion" },
  { id: "gantt", name: "Gantt", cat: "Time", shape: "gantt", desc: "Workplan" },
  { id: "timeline", name: "Timeline", cat: "Time", shape: "gantt", desc: "Milestones" },
];

export const CHART_CATS = [...new Set(CHART_TYPES.map((t) => t.cat))];

export function chartMeta(id) {
  return CHART_TYPES.find((t) => t.id === id) || CHART_TYPES[0];
}

export const FONT = "'Plus Jakarta Sans', 'Segoe UI', sans-serif";
export const SERIF = "'Fraunces', Georgia, serif";
export const MONO = "'IBM Plex Mono', ui-monospace, monospace";
